# Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Your custom API properties
app.api.key=${API_KEY}
app.api.url=${API_URL}

# Security
app.security.username=${SECURITY_USER_NAME}
app.security.password=${SECURITY_USER_PASSWORD}